version: '3.8'

services:
  blaha-homepage:
    build: .
    container_name: blaha-homepage
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5001:8100"
    volumes:
      - ./data:/app/data
